#!/usr/bin/python3
import numpy as np

def monte_carlo_sin(n):
    np.random.seed(0)  # for reproducibility
    x = np.random.uniform(0, np.pi, n)
    y = np.sin(x)
    return np.pi * np.mean(y)


ns = [10, 20, 40, 80, 160]
for n in ns:
    print(f"n = {n}: Y(n) = {monte_carlo_sin(n):.3f}")
